### ISSUE TITLE
Provide a flatpak manifest

### ISSUE THREAD

**Issue by danrabbit** [elementary/tasks#156]
See https://github.com/elementary/calculator/blob/master/io.elementary.calculator.yml as an example

**Comment by marbetschar** [comment]
@danrabbit I'm happy to create the manifest file - but how do I test if it works correctly? Never packed for Flatpak, but I'm eager to learn :)

**Comment by Marukesu** [comment]
So, i made that manifest yesterday, but i can't fully test it because if incompatibles DBus interfaces of EDS from hera.
```YAML
app-id: io.elementary.tasks
runtime: org.gnome.Platform 
runtime-version: '3.38'
base: io.elementary.BaseApp
base-version: juno-20.08
sdk: org.gnome.Sdk
command: io.elementary.tasks
finish-args:
  - '--share=ipc'
  - '--socket=fallback-x11'
  - '--socket=wayland'

  # Nedded for perfer-color-scheme
  - '--system-talk-name=org.freedesktop.Accounts'

  # EDS DBus interfaces
  - '--talk-name=org.gnome.evolution.dataserver.AddressBook9'
  - '--talk-name=org.gnome.evolution.dataserver.Calendar8'
  - '--talk-name=org.gnome.evolution.dataserver.Source5'
  - '--talk-name=org.gnome.evolution.dataserver.Subprocess.Backend.*'

  - '--metadata=X-DConf=migrate-path=/io/elementary/tasks/'
cleanup:
  - '/include'
  - '/lib/pkgconfig'
  - '/lib/debug'
  - '/share/vala'
  - '*a'
  - '*.la'
modules:
  - name: libical
    buildsystem: cmake-ninja
    config-opts:
      - '-DCMAKE_BUILD_TYPE=Release'
      - '-DCMAKE_INSTALL_LIBDIR=/app/lib'
      - '-DBUILD_SHARED_LIBS=ON'
      - '-DICAL_GLIB=true'
      - '-DICAL_GLIB_VAPI=true'
      - '-DGOBJECT_INTROSPECTION=true'
      - '-DICAL_BUILD_DOCS=false'
    sources:
      - type: git
        url: https://github.com/libical/libical.git
        tag: v3.0.8

  - name: evolution-data-server
    buildsystem: cmake-ninja
    cleanup:
      - /lib/evolution-data-server/*-backends
      - /libexec
      - /share/dbus-1/services
    config-opts:
      - '-DCMAKE_BUILD_TYPE=Release'
      - '-DENABLE_GTK=ON'
      - '-DENABLE_CANBERRA=OFF'
      - '-DENABLE_GOA=OFF'
      - '-DENABLE_GOOGLE=ON'
      - '-DENABLE_VALA_BINDINGS=ON'
      - '-DENABLE_WEATHER=OFF'
      - '-DWITH_OPENLDAP=OFF'
      - '-DWITH_LIBDB=OFF'
      - '-DENABLE_INTROSPECTION=ON'
      - '-DENABLE_INSTALLED_TESTS=OFF'
      - '-DENABLE_GTK_DOC=OFF'
      - '-DENABLE_EXAMPLES=OFF'
    sources:
      - type: git
        url: https://gitlab.gnome.org/GNOME/evolution-data-server.git
        tag: '3.38.1'
    modules:
      - name: intltool
        cleanup:
          - '*'
        sources:
          - type: archive
            url: https://launchpad.net/intltool/trunk/0.51.0/+download/intltool-0.51.0.tar.gz
            md5: 12e517cac2b57a0121cda351570f1e63
      - name: libgdata
        buildsystem: meson
        config-opts:
          - '-Dalways_build_tests=false'
          - '-Dgoa=disabled'
        sources:
          - type: git
            url: https://gitlab.gnome.org/GNOME/libgdata.git
            tag: '0.17.13'

  - name: handy
    buildsystem: meson
    config-opts:
      - '-Dexamples=false'
      - '-Dtests=false'
    sources:
      - type: git
        url: https://gitlab.gnome.org/GNOME/libhandy.git
        tag: '1.0.0'

  - name: tasks
    buildsystem: meson
    sources:
      - type: git
        url: https://github.com/elementary/tasks.git
```
